import type { Metadata } from 'next';
import { ThemeProvider as NextThemesProvider } from 'next-themes';
import { ModeToggle } from '@/components/ModeToggle';
import { Toaster } from '@/components/ui/sonner';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='uk'>
			<body className={`min-h-screen ${inter.className}`}>
				<NextThemesProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
				>
					<ModeToggle className='absolute top-6 right-6' />
					{children}
					<Toaster expand={true} richColors />
				</NextThemesProvider>
			</body>
		</html>
	);
}
